import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteProjectContext from "./project-context.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteYouTube from "./youtube.schema";
import * as sqliteLinkedIn from "./linkedin.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as sqliteGrowth from "./growth.schema";
import * as sqliteGrowthInsights from "./growth-insights.schema";
import * as sqliteGrowthWorkstreams from "./growth-workstreams.schema";
import * as sqliteGrowthActions from "./growth-actions.schema";
import * as sqliteGrowthEvidenceSeries from "./growth-evidence-series.schema";
import * as sqliteGrowthChangeEvents from "./growth-change-events.schema";
import * as sqliteGrowthMeasurements from "./growth-measurements.schema";
import * as sqliteGrowthReports from "./growth-reports.schema";
import * as sqliteGrowthAiBriefs from "./growth-ai-briefs.schema";
import * as sqliteGrowthAssessments from "./growth-assessments.schema";
import * as sqliteGrowthAssessmentInvestigations from "./growth-assessment-investigations.schema";
import * as sqlitePromptExplorerSnapshots from "./prompt-explorer-snapshots.schema";
import * as pgApp from "./pg/app.schema";
import * as pgProjectContext from "./pg/project-context.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgYouTube from "./pg/youtube.schema";
import * as pgLinkedIn from "./pg/linkedin.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as pgGrowth from "./pg/growth.schema";
import * as pgGrowthInsights from "./pg/growth-insights.schema";
import * as pgGrowthWorkstreams from "./pg/growth-workstreams.schema";
import * as pgGrowthActions from "./pg/growth-actions.schema";
import * as pgGrowthEvidenceSeries from "./pg/growth-evidence-series.schema";
import * as pgGrowthChangeEvents from "./pg/growth-change-events.schema";
import * as pgGrowthMeasurements from "./pg/growth-measurements.schema";
import * as pgGrowthReports from "./pg/growth-reports.schema";
import * as pgGrowthAiBriefs from "./pg/growth-ai-briefs.schema";
import * as pgGrowthAssessments from "./pg/growth-assessments.schema";
import * as pgGrowthAssessmentInvestigations from "./pg/growth-assessment-investigations.schema";
import * as pgPromptExplorerSnapshots from "./pg/prompt-explorer-snapshots.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteProjectContext &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGa4 &
  typeof sqliteGsc &
  typeof sqliteYouTube &
  typeof sqliteLinkedIn &
  typeof sqliteTelemetry &
  typeof sqliteGrowth &
  typeof sqliteGrowthInsights &
  typeof sqliteGrowthWorkstreams &
  typeof sqliteGrowthActions &
  typeof sqliteGrowthEvidenceSeries &
  typeof sqliteGrowthChangeEvents &
  typeof sqliteGrowthMeasurements &
  typeof sqliteGrowthReports &
  typeof sqliteGrowthAiBriefs &
  typeof sqliteGrowthAssessments &
  typeof sqliteGrowthAssessmentInvestigations &
  typeof sqlitePromptExplorerSnapshots;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgProjectContext,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGa4,
        ...pgGsc,
        ...pgYouTube,
        ...pgLinkedIn,
        ...pgTelemetry,
        ...pgGrowth,
        ...pgGrowthInsights,
        ...pgGrowthWorkstreams,
        ...pgGrowthActions,
        ...pgGrowthEvidenceSeries,
        ...pgGrowthChangeEvents,
        ...pgGrowthMeasurements,
        ...pgGrowthReports,
        ...pgGrowthAiBriefs,
        ...pgGrowthAssessments,
        ...pgGrowthAssessmentInvestigations,
        ...pgPromptExplorerSnapshots,
      }
    : {
        ...sqliteApp,
        ...sqliteProjectContext,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGa4,
        ...sqliteGsc,
        ...sqliteYouTube,
        ...sqliteLinkedIn,
        ...sqliteTelemetry,
        ...sqliteGrowth,
        ...sqliteGrowthInsights,
        ...sqliteGrowthWorkstreams,
        ...sqliteGrowthActions,
        ...sqliteGrowthEvidenceSeries,
        ...sqliteGrowthChangeEvents,
        ...sqliteGrowthMeasurements,
        ...sqliteGrowthReports,
        ...sqliteGrowthAiBriefs,
        ...sqliteGrowthAssessments,
        ...sqliteGrowthAssessmentInvestigations,
        ...sqlitePromptExplorerSnapshots,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  projectContextSections,
  projectCompetitors,
  projectKeyPages,
  projectResearchLog,
  audits,
  auditPages,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  user,
  session,
  account,
  apikey,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  ga4Connections,
  gscConnections,
  youtubeConnections,
  linkedinPageConnections,
  linkedinPageOverviewCaches,
  linkedinPageImports,
  linkedinPagePostMetrics,
  telemetryState,
  growthProjectSettings,
  growthRuns,
  growthMonthlyCycleOperatorObservations,
  growthSignals,
  growthInsights,
  growthInsightSignals,
  growthRecommendations,
  growthRecommendationInsights,
  growthRecommendationTargets,
  growthRecommendationSteps,
  growthRecommendationSignalLinks,
  growthWorkstreams,
  growthActions,
  growthActionTargets,
  growthActionEvents,
  growthActionEvidence,
  growthEvidenceSeries,
  growthEvidencePoints,
  growthChangeEvents,
  growthChangeEventUrls,
  growthActionChanges,
  growthMeasurementPlans,
  growthMeasurementPlanAnchors,
  growthMeasurementMetrics,
  growthMeasurementObservations,
  growthMeasurementResults,
  growthMeasurementResultChanges,
  growthReports,
  growthReportSections,
  growthReportActions,
  growthReportMeasurementResults,
  growthAiBriefs,
  growthAiBriefClaims,
  growthAiBriefCitationSources,
  growthAiBriefCitations,
  growthAiBriefSteps,
  growthAiBriefCaveats,
  growthAssessments,
  growthAssessmentOptions,
  growthAssessmentInvestigations,
  growthAssessmentInvestigationFindings,
  growthAssessmentInvestigationEvidence,
  promptExplorerSnapshots,
  promptExplorerSnapshotModels,
  promptExplorerSnapshotCitations,
  promptExplorerSnapshotFanOutQueries,
} = schema;
