import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteProjectContext from "./project-context.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as sqliteGrowth from "./growth.schema";
import * as sqliteGrowthInsights from "./growth-insights.schema";
import * as sqliteGrowthActions from "./growth-actions.schema";
import * as sqliteGrowthChangeEvents from "./growth-change-events.schema";
import * as sqliteGrowthMeasurements from "./growth-measurements.schema";
import * as sqliteGrowthReports from "./growth-reports.schema";
import * as pgApp from "./pg/app.schema";
import * as pgProjectContext from "./pg/project-context.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as pgGrowth from "./pg/growth.schema";
import * as pgGrowthInsights from "./pg/growth-insights.schema";
import * as pgGrowthActions from "./pg/growth-actions.schema";
import * as pgGrowthChangeEvents from "./pg/growth-change-events.schema";
import * as pgGrowthMeasurements from "./pg/growth-measurements.schema";
import * as pgGrowthReports from "./pg/growth-reports.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteProjectContext &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGa4 &
  typeof sqliteGsc &
  typeof sqliteTelemetry &
  typeof sqliteGrowth &
  typeof sqliteGrowthInsights &
  typeof sqliteGrowthActions &
  typeof sqliteGrowthChangeEvents &
  typeof sqliteGrowthMeasurements &
  typeof sqliteGrowthReports;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgProjectContext,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGa4,
        ...pgGsc,
        ...pgTelemetry,
        ...pgGrowth,
        ...pgGrowthInsights,
        ...pgGrowthActions,
        ...pgGrowthChangeEvents,
        ...pgGrowthMeasurements,
        ...pgGrowthReports,
      }
    : {
        ...sqliteApp,
        ...sqliteProjectContext,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGa4,
        ...sqliteGsc,
        ...sqliteTelemetry,
        ...sqliteGrowth,
        ...sqliteGrowthInsights,
        ...sqliteGrowthActions,
        ...sqliteGrowthChangeEvents,
        ...sqliteGrowthMeasurements,
        ...sqliteGrowthReports,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  projectContextSections,
  projectCompetitors,
  projectKeyPages,
  projectResearchLog,
  audits,
  auditPages,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  user,
  session,
  account,
  apikey,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  ga4Connections,
  gscConnections,
  telemetryState,
  growthProjectSettings,
  growthRuns,
  growthSignals,
  growthInsights,
  growthInsightSignals,
  growthRecommendations,
  growthRecommendationInsights,
  growthRecommendationTargets,
  growthRecommendationSteps,
  growthRecommendationSignalLinks,
  growthActions,
  growthActionTargets,
  growthActionEvents,
  growthChangeEvents,
  growthChangeEventUrls,
  growthActionChanges,
  growthMeasurementPlans,
  growthMeasurementPlanAnchors,
  growthMeasurementMetrics,
  growthMeasurementObservations,
  growthMeasurementResults,
  growthMeasurementResultChanges,
  growthReports,
  growthReportSections,
  growthReportActions,
  growthReportMeasurementResults,
} = schema;
